# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
        exclude: ^(src/fscacher/_version\.py|versioneer\.py)$
-   repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
    -   id: isort
        exclude: ^(src/fscacher/_version\.py|versioneer\.py)$
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-builtins
          - flake8-unused-arguments
        exclude: ^(src/fscacher/_version\.py|versioneer\.py)$
