name: Benchmark

on:
    pull_request:
    push:

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                python-version:
                    - '3.6'
                    - '3.7'
                    - '3.8'
                    - '3.9'
                    - pypy3
        steps:
            - name: Check out repository
              uses: actions/checkout@v2
              with:
                fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip wheel
                python -m pip install --upgrade --upgrade-strategy=eager \
                    asv virtualenv

            - name: Set up machine profile
              run: asv machine --yes

            - name: Save comparison points as GitHub refs
              run: |
                # If this is a PR run, then HEAD is a refs/pull/:number/merge
                # ref and HEAD^1 is the target that the PR will be merged into.

                # If this is a push run, then HEAD is the most recently-pushed
                # commit and HEAD^1 is the commit before it (which may or may
                # not be the previous HEAD for the branch, depending on whether
                # multiple commits were pushed at once).

                git update-ref refs/bm/pr HEAD
                git update-ref refs/bm/merge-target HEAD^1

            - name: Run benchmarks on newest code
              run: asv run HEAD

            - name: Check out previous code
              run: git checkout --force refs/bm/merge-target

            - name: Run benchmarks on previous code
              run: asv run HEAD

            - name: Compare benchmarks on previous & newest code
              run: asv compare refs/bm/merge-target refs/bm/pr
