name: Test

on:
    pull_request:
    push:
    schedule:
        - cron: '0 6 * * *'

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os:
                    - macos-latest
                    - ubuntu-latest
                    - windows-latest
                python-version:
                    - '3.6'
                    - '3.7'
                    - '3.8'
                    - '3.9'
                    - '3.10'
                    - pypy-3.7
                toxenv:
                    - py
                include:
                    - os: ubuntu-latest
                      python-version: '3.6'
                      toxenv: py-dev
        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip wheel
                python -m pip install --upgrade --upgrade-strategy=eager tox

            - name: Install git annex (Ubuntu)
              if: startsWith(matrix.os, 'ubuntu')
              run: sudo apt-get update && sudo apt-get install -y git-annex

            - name: Install git annex (macOS)
              if: startsWith(matrix.os, 'macos')
              run: brew install git-annex

            - name: Run tests
              if: matrix.toxenv == 'py'
              run: tox -e py -- --cov-report=xml

            - name: Run generic tests
              if: matrix.toxenv != 'py'
              run: tox -e ${{ matrix.toxenv }}

            - name: Upload coverage to Codecov
              if: matrix.toxenv == 'py'
              uses: codecov/codecov-action@v1
              with:
                  fail_ci_if_error: false
